### ISSUE TITLE
inconsistent "story" dialog 

### ISSUE THREAD

**Issue by etshy** [ivanaedler/MIMPUT#34] opened 2017-06-15 22:12 UTC
I think there are many bubble dialog that are wrong.
like at the start, when you juste talk with toadworth, It's like you're having a scene with him but no, It must be a "real" dialog.

I don't know if i can attach a screen, but here is one
https://puu.sh/wl9D5/d8f8362e94.png

**Comment by ivanaedler** [comment] 2017-07-14 20:20
Hmmmm..... I know what is happening. The problem is the custom dialogues that happens when she into a creature scene. Once we see a dialogue in goomba scene 1, for example, when she into the same scene again, she starts talking random. This must not happen in 'normal dialogue' scenes. Marked as bug.

PS: I havent seen it before because I was working in version 3.39, with the new Peachy character for the game.

**Comment by ivanaedler** [comment] 2018-01-09 14:49
Fixed! But beware! If you activate 'Funny Dialogues', it will be changed as its the expected behavior!

**Closed by ivanaedler** 2018-01-09 14:49 UTC
Labels: bug

**Comment by etshy** [comment] 2018-01-09 17:23
ooh I forgot that.
I'll have to retest that in the next release so (or maybe in the latest ?)
